name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy pylint

    - name: Format code with black
      run: |
        black --line-length 88 --target-version py38 .

    - name: Sort imports with isort
      run: |
        isort --profile black .

    - name: Lint with flake8
      run: |
        flake8 --max-line-length=88 --extend-ignore=E203,W503 .

    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs . || true

    - name: Lint with pylint
      run: |
        pylint --disable=all --enable=unused-import,unused-variable,undefined-variable . || true

    - name: Check for auto-formatting changes
      run: |
        if ! git diff --exit-code; then
          echo "Code formatting changes detected. Please run 'black .' and 'isort .' locally."
          exit 1
        fi
